server:
  port: 9026
spring: 
  datasource: 
    url: jdbc:h2:file:~/h2-db/exampledb;TRACE_LEVEL_FILE=0
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console: 
      enabled: true
      path: /h2