server:
  port: 9026
spring: 
  datasource: 
    url: jdbc:h2:file:./src/main/resources/db/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console: 
      enabled: true
      path: /h2